server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie_sys
    username: root
    password: Jzy969811
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      lettuce:
        pool:
          max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
          max-idle: 8 # 连接池中的最大空闲连接
          min-idle: 0 # 连接池中的最小空闲连接
        shutdown-timeout: 100ms # 连接池关闭的超时时间
      timeout: 60s # 连接超时时间
      database: 0 # Redis 数据库索引
      password: yourpassword # Redis 密码
      host: localhost # Redis 服务器地址
      port: 6379 # Redis 服务器连接端口
  application:
    name: movie
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}