#server:
#  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie_sys
    username: root
    password: Jzy969811
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: login
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}